version: '3.9'

services:
  redis:
    image: redis:6-alpine
    restart: always
    container_name: microservices_redis
    ports:
      - "6379:6379"
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_DATABASE=e_commerce
      - MYSQL_ROOT_PASSWORD=
    ports:
      - '3306:3306'